name: Deploy to GitHub Pages

concurrency: production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version (*.*.*)'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.16.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'npm'
          
      - run: npm install
        working-directory: web

      - run: npm run build
        working-directory: web

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'

      - uses: actions/deploy-pages@v4
