name: Deploy to GitHub Pages

concurrency: production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version (*.*.*)'
        required: true

jobs:
  build_and_deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./web
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.16.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          
      - run: npm install

      - run: npm run build

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'

      - uses: actions/deploy-pages@v4
